kind: Deployment
apiVersion: apps/v1
metadata:
  name: webdocker
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/webdocker
  #resourceVersion: '132070'
  generation: 1
  creationTimestamp: '2020-11-17T13:51:42Z'
  labels:
    appgroup: ''
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
    description: webdocker222111111
spec:
  
  selector:
    matchLabels:
      app: webdocker
      version: v1
  template:
    metadata:
      labels:
        app: webdocker
        version: v1
    spec:
      containers:
        - name: container-0
          image: 'swr.ap-southeast-1.myhuaweicloud.com/dev-hk/webdocker:latest'
          env:
            - name: PAAS_APP_NAME
              value: webdocker
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 09cfa301f38010582f03c00ac54c8b92
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      affinity: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      dnsConfig:
        options:
          - name: timeout
            value: ''
          - name: ndots
            value: '5'
          - name: single-request-reopen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600