kind: Deployment
apiVersion: apps/v1
metadata:
  name: webdocker
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/webdocker
  uid: b4bb801b-a6fa-4055-91c1-a8cc5849feac
  resourceVersion: '132070'
  generation: 1
  creationTimestamp: '2020-11-17T13:51:42Z'
  labels:
    appgroup: ''
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
    description: webdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdocker
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-11-17T13:51:42Z'
      lastTransitionTime: '2020-11-17T13:51:42Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-11-17T13:51:46Z'
      lastTransitionTime: '2020-11-17T13:51:42Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "webdocker-6dc8495778" has successfully progressed.
